#!/usr/bin/env bash
set -e

npx elm-format --validate src/ tests/
deno fmt --check functions/ scripts/
npx elm make src/Main.elm --output=/dev/null
npx elm-test
deno check functions/ scripts/
deno test functions/
